### ISSUE TITLE
Training Code on multi-gpu

### ISSUE THREAD

**Issue by Amo5** [PatrickTUM/UnCRtainTS#2]
Can you provide the training code on multi-gpu?

**Comment by PatrickTUM** [comment]
Hi @Amo5,

thanks for your inquiry! Unfortunately, due to a change in my position, I do no longer have access to any multi-GPU machines. That would make developing and debugging for multi-GPU processing challenging. However, if you may at some point make a pull request including those adjustments, I'd gladly include your modifications into the repository or a branch. Cheers, Patrick.

**Comment by PatrickTUM** [comment]
Closing this issue for now, feel free to send a pull request or re-open as needed.
